/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DropdownItem: typeof import('./../../views/components/DropdownItem.vue')['default']
    DropdownMenu: typeof import('./../../views/components/DropdownMenu.vue')['default']
    EmptyTableRow: typeof import('./../../views/components/listings-table/empty-table-row.vue')['default']
    GithubLogo: typeof import('./../../views/components/github-logo.vue')['default']
    ItemSearch: typeof import('./../../views/components/item-search.vue')['default']
    ItemSelect: typeof import('./../../views/components/item-select.vue')['default']
    ItemTableData: typeof import('./../../views/components/listings-table/item-table-data.vue')['default']
    LayoutMain: typeof import('@/views/layouts/main/layout-main.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    ListingTable: typeof import('./../../views/components/listings-table/listing-table.vue')['default']
    ListingTableRow: typeof import('./../../views/components/listings-table/listing-table-row.vue')['default']
    NoteTableData: typeof import('./../../views/components/listings-table/note-table-data.vue')['default']
    Pagination: typeof import('./../../views/components/pagination.vue')['default']
    PriceTableData: typeof import('./../../views/components/listings-table/price-table-data.vue')['default']
    TimestampTableData: typeof import('./../../views/components/listings-table/timestamp-table-data.vue')['default']
    UsernameTableData: typeof import('./../../views/components/listings-table/username-table-data.vue')['default']
  }
}
