/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GithubLogo: typeof import('./../../views/components/github-logo.vue')['default']
    ItemSearch: typeof import('./../../views/components/item-search.vue')['default']
    LayoutMain: typeof import('@/views/layouts/main/layout-main.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    Pagination: typeof import('./../../views/components/pagination.vue')['default']
  }
}
